# Generated by Django 3.2.5 on 2021-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('portfolio', models.CharField(max_length=50)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('coverletter', models.CharField(max_length=100)),
            ],
        ),
    ]
