# Generated by Django 3.2.5 on 2021-07-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='portfolio',
        ),
    ]
