# Generated by Django 4.2.1 on 2023-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=30, null=True),
        ),
    ]
