# Generated by Django 3.2.5 on 2021-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_apply_job_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='cv',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
