# Generated by Django 3.2.5 on 2021-07-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_apply_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
