# Generated by Django 3.2.5 on 2021-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210706_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='cv',
            field=models.FileField(null=True, upload_to='Upload Resumes'),
        ),
    ]
