# Generated by Django 3.2.5 on 2021-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_apply_job_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
